# File: .readthedocs.yaml

version: 2

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt
    - method: setuptools
      path: ./